# Generated by Django 5.1.1 on 2024-09-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_driver_user_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
